---
#====================================================================================================
# Description : Platform Engineering Coding Challenge - Setup core networking
#====================================================================================================

AWSTemplateFormatVersion: "2010-09-09"
Description: "Platform Engineering Coding Challenge"

# Parameters

Parameters:
  VPCCIDR:
    Description: VPC Network CIDR
    Type: String
    Default: "10.0.0.0/16"
  VPCSubnetMask:
    Description: VPC subnet mask bits (8 is /24)
    Type: Number
    Default: 8
  NumberOfNATGateways:
    Description: How many NAT Gateways should be configured
    Type: String
    Default: "1"
    AllowedValues:
      - "0"
      - "1"
      - "2"
      - "3"
  VPCFlowLogsS3Bucket:
    Description: Bucket name for Flow Logs
    Default: "vpc-flow-logs-bucket-santosh-619170903429"
    Type: String
  VPCFlowLogsSwitch:
    Description: Variable to control if we should enable VPC Flow Logs
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
  VPCFlowLogsLogDestinationType:
    Description: Flow Log Type
    Type: String
    Default: s3
  Environment:
    Description: Which environment the resources will be deployed
    Type: String
    Default: "Dev"
    AllowedValues:
      - "Dev"
      - "Stage"
      - "Prod"
  RemoteAccessCIDR:
    Description: Remote address CIDR
    Type: String
    Default: "0.0.0.0/0"

# Conditions

Conditions:
  IsNATAEnabled:
    !Or [
      !Equals [!Ref NumberOfNATGateways, "1"],
      !Equals [!Ref NumberOfNATGateways, "2"],
      !Equals [!Ref NumberOfNATGateways, "3"],
    ]
  IsNATBEnabled:
    !Or [
      !Equals [!Ref NumberOfNATGateways, "2"],
      !Equals [!Ref NumberOfNATGateways, "3"],
    ]
  IsNATCEnabled: !Equals [!Ref NumberOfNATGateways, "3"]
  IsNATARouteableFromB:
    !And [Condition: IsNATAEnabled, !Not [Condition: IsNATBEnabled]]
  IsNATARouteableFromC:
    !And [Condition: IsNATAEnabled, !Not [Condition: IsNATCEnabled]]
  EnableVPCFlowLogs:
    !And [
      !Not [!Equals [!Ref VPCFlowLogsLogDestinationType, ""]],
      !Equals [!Ref VPCFlowLogsSwitch, "true"],
    ]

# Resources

Resources:
  # Create VPC

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !Sub "${VPCCIDR}"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-vpc"

  # Create NACLs to allow external traffic

  PublicNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-public-nacl"
      VpcId:
        Ref: VPC

  PermitAnyFromPublic:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Sub ${RemoteAccessCIDR}
      Egress: "true"
      NetworkAclId:
        Ref: PublicNACL
      Protocol: "-1"
      RuleAction: allow
      RuleNumber: "100"

  PermitAnyToPublic:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Sub ${RemoteAccessCIDR}
      NetworkAclId:
        Ref: PublicNACL
      Protocol: "-1"
      RuleAction: allow
      RuleNumber: "100"

  PrivateNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-private-nacl"
      VpcId:
        Ref: VPC

  PermitAnyFromPrivate:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Sub ${RemoteAccessCIDR}
      Egress: "true"
      NetworkAclId:
        Ref: PrivateNACL
      Protocol: "-1"
      RuleAction: allow
      RuleNumber: "100"

  PermitAnyToPrivate:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Sub ${RemoteAccessCIDR}
      NetworkAclId:
        Ref: PrivateNACL
      Protocol: "-1"
      RuleAction: allow
      RuleNumber: "100"

  # Create Public Subnets

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs:
              Ref: AWS::Region
      CidrBlock:
        !Select [0, !Cidr [!Sub "${VPCCIDR}", 12, !Sub "${VPCSubnetMask}"]]
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-public-subnet-a"
      VpcId:
        Ref: VPC

  PublicSubnetANACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: PublicNACL
      SubnetId:
        Ref: PublicSubnetA

  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicRouteTableA
      SubnetId:
        Ref: PublicSubnetA

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs:
              Ref: AWS::Region
      CidrBlock:
        !Select [1, !Cidr [!Sub "${VPCCIDR}", 12, !Sub "${VPCSubnetMask}"]]
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-public-subnet-b"
      VpcId:
        Ref: VPC

  PublicSubnetBNACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: PublicNACL
      SubnetId:
        Ref: PublicSubnetB

  PublicSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicRouteTableB
      SubnetId:
        Ref: PublicSubnetB

  PublicSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 2
          - Fn::GetAZs:
              Ref: AWS::Region
      CidrBlock:
        !Select [2, !Cidr [!Sub "${VPCCIDR}", 12, !Sub "${VPCSubnetMask}"]]
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-public-subnet-c"
      VpcId:
        Ref: VPC

  PublicSubnetCNACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: PublicNACL
      SubnetId:
        Ref: PublicSubnetC

  PublicSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicRouteTableC
      SubnetId:
        Ref: PublicSubnetC

  # Create Private Subnets

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs:
              Ref: AWS::Region
      CidrBlock:
        !Select [4, !Cidr [!Sub "${VPCCIDR}", 12, !Sub "${VPCSubnetMask}"]]
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-private-subnet-a"
      VpcId:
        Ref: VPC

  PrivateSubnetANACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: PrivateNACL
      SubnetId:
        Ref: PrivateSubnetA

  PrivateSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTableA
      SubnetId:
        Ref: PrivateSubnetA

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs:
              Ref: AWS::Region
      CidrBlock:
        !Select [5, !Cidr [!Sub "${VPCCIDR}", 12, !Sub "${VPCSubnetMask}"]]
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-private-subnet-b"
      VpcId:
        Ref: VPC

  PrivateSubnetBNACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: PrivateNACL
      SubnetId:
        Ref: PrivateSubnetB

  PrivateSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTableB
      SubnetId:
        Ref: PrivateSubnetB

  PrivateSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 2
          - Fn::GetAZs:
              Ref: AWS::Region
      CidrBlock:
        !Select [6, !Cidr [!Sub "${VPCCIDR}", 12, !Sub "${VPCSubnetMask}"]]
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-private-subnet-c"
      VpcId:
        Ref: VPC

  PrivateSubnetCNACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: PrivateNACL
      SubnetId:
        Ref: PrivateSubnetC

  PrivateSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTableC
      SubnetId:
        Ref: PrivateSubnetC

  # Create Internet Gateway, NAT Gateway and EIPs

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-internet-gateway"

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: InternetGateway
      VpcId:
        Ref: VPC

  NATGatewayEIPA:
    Type: AWS::EC2::EIP
    Condition: IsNATAEnabled
    DependsOn: VPC
    Properties:
      Domain: VPC

  NATGatewayA:
    Type: AWS::EC2::NatGateway
    Condition: IsNATAEnabled
    DependsOn:
      - NATGatewayEIPA
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-nat-gateway-a"
      AllocationId: !Sub "${NATGatewayEIPA.AllocationId}"
      SubnetId: !Ref PublicSubnetA

  PrivateDefaultRouteA:
    Type: AWS::EC2::Route
    Condition: IsNATAEnabled
    Properties:
      DestinationCidrBlock: !Sub ${RemoteAccessCIDR}
      NatGatewayId: !Ref NATGatewayA
      RouteTableId: !Ref PrivateRouteTableA

  NATGatewayEIPB:
    Type: AWS::EC2::EIP
    Condition: IsNATBEnabled
    DependsOn: VPC
    Properties:
      Domain: VPC

  NATGatewayB:
    Type: AWS::EC2::NatGateway
    Condition: IsNATBEnabled
    DependsOn:
      - NATGatewayEIPB
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-nat-gateway-b"
      AllocationId: !Sub "${NATGatewayEIPB.AllocationId}"
      SubnetId: !Ref PublicSubnetB

  PrivateDefaultRouteB:
    Type: AWS::EC2::Route
    Condition: IsNATBEnabled
    Properties:
      DestinationCidrBlock: !Sub ${RemoteAccessCIDR}
      NatGatewayId: !Ref NATGatewayB
      RouteTableId: !Ref PrivateRouteTableB

  PrivateDefaultRouteBAlt:
    Type: AWS::EC2::Route
    Condition: IsNATARouteableFromB
    Properties:
      DestinationCidrBlock: !Sub ${RemoteAccessCIDR}
      NatGatewayId: !Ref NATGatewayA
      RouteTableId: !Ref PrivateRouteTableB

  NATGatewayEIPC:
    Type: AWS::EC2::EIP
    Condition: IsNATCEnabled
    DependsOn: VPC
    Properties:
      Domain: VPC

  NATGatewayC:
    Type: AWS::EC2::NatGateway
    Condition: IsNATCEnabled
    DependsOn:
      - NATGatewayEIPC
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-nat-gateway-c"
      AllocationId: !Sub "${NATGatewayEIPC.AllocationId}"
      SubnetId: !Ref PublicSubnetC

  # Create routes in route tables

  PrivateDefaultRouteC:
    Type: AWS::EC2::Route
    Condition: IsNATCEnabled
    Properties:
      DestinationCidrBlock: !Sub ${RemoteAccessCIDR}
      NatGatewayId: !Ref NATGatewayC
      RouteTableId: !Ref PrivateRouteTableC

  PrivateDefaultRouteCAlt:
    Type: AWS::EC2::Route
    Condition: IsNATARouteableFromC
    Properties:
      DestinationCidrBlock: !Sub ${RemoteAccessCIDR}
      NatGatewayId: !Ref NATGatewayA
      RouteTableId: !Ref PrivateRouteTableC

  PublicRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-public-route-table-a"
      VpcId:
        Ref: VPC

  PublicDefaultRouteA:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      DestinationCidrBlock: !Sub ${RemoteAccessCIDR}
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: PublicRouteTableA

  PublicRouteTableB:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-public-route-table-b"
      VpcId:
        Ref: VPC

  PublicDefaultRouteB:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      DestinationCidrBlock: !Sub ${RemoteAccessCIDR}
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: PublicRouteTableB

  PublicRouteTableC:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-public-route-table-c"
      VpcId:
        Ref: VPC

  PublicDefaultRouteC:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      DestinationCidrBlock: !Sub ${RemoteAccessCIDR}
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: PublicRouteTableC

  PrivateRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-private-route-table-a"
      VpcId:
        Ref: VPC

  PrivateRouteTableB:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-private-route-table-b"
      VpcId:
        Ref: VPC

  PrivateRouteTableC:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-private-route-table-c"
      VpcId:
        Ref: VPC

  # Enable VPC flow logs and create S3 bucket to store logs

  VPCFlowLogsS3BucketObject:
    Type: "AWS::S3::Bucket"
    Condition: EnableVPCFlowLogs
    Properties:
      BucketName: !Sub "${VPCFlowLogsS3Bucket}"
      Tags:
        - Key: Name
          Value: !Sub "${VPCFlowLogsS3Bucket}"
        - Key: VpcId
          Value: !Ref VPC

  FlowLog:
    Type: AWS::EC2::FlowLog
    Condition: EnableVPCFlowLogs
    Properties:
      LogDestination: !Sub "arn:aws:s3:::${VPCFlowLogsS3Bucket}/"
      LogDestinationType: !Ref VPCFlowLogsLogDestinationType
      ResourceId: !Ref VPC
      ResourceType: VPC
      TrafficType: ALL
    DependsOn: VPCFlowLogsS3BucketObject

  # Create security group

  WebserverSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Sub "${Environment}-webserver-sg"
      GroupDescription: "Webserver Security Group"
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-webserver-sg"

  WebserverSGIngressTcp22:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "SSH Port"
      GroupId:
        Ref: WebserverSG
      IpProtocol: tcp
      FromPort: "22"
      ToPort: "22"
      CidrIp: !Sub "${RemoteAccessCIDR}"

  WebserverSGIngressTcp80:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "HTTP Port"
      GroupId:
        Ref: WebserverSG
      IpProtocol: tcp
      FromPort: "80"
      ToPort: "80"
      CidrIp: !Sub "${RemoteAccessCIDR}"

  WebserverSGIngressTcp8080:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "Port 8080"
      GroupId:
        Ref: WebserverSG
      IpProtocol: tcp
      FromPort: "8080"
      ToPort: "8080"
      CidrIp: !Sub "${RemoteAccessCIDR}"

Outputs:

  VpcId:
    Value: !Ref VPC
    Export:
      Name: !Sub '${Environment}-vpc-id'
  VPCRegion:
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${Environment}-vpc-region'
  VPCCIDRBlock:
    Value: !Sub '${VPCCIDR}'
    Export:
      Name: !Sub '${Environment}-vpc-CIDR-block'
  PublicSubnetA:
    Value:
      Ref: PublicSubnetA
    Export:
      Name: !Sub '${Environment}-public-sn-a'
  PublicSubnetB:
    Value:
      Ref: PublicSubnetB
    Export:
      Name: !Sub '${Environment}-public-sn-b'
  PublicSubnetC:
    Value:
      Ref: PublicSubnetC
    Export:
      Name: !Sub '${Environment}-public-sn-c'
  PrivateSubnetA:
    Value:
      Ref: PrivateSubnetA
    Export:
      Name: !Sub '${Environment}-private-sn-a'
  PrivateSubnetB:
    Value:
      Ref: PrivateSubnetB
    Export:
      Name: !Sub '${Environment}-private-sn-b'
  PrivateSubnetC:
    Value:
      Ref: PrivateSubnetC
    Export:
      Name: !Sub '${Environment}-private-sn-c'
  PublicRouteTableA:
    Value:
      Ref: PublicRouteTableA
    Export:
      Name: !Sub '${Environment}-public-rt-a'
  PublicRouteTableB:
    Value:
      Ref: PublicRouteTableB
    Export:
      Name: !Sub '${Environment}-public-rt-b'
  PublicRouteTableC:
    Value:
      Ref: PublicRouteTableC
    Export:
      Name: !Sub '${Environment}-public-rt-c'
  PrivateRouteTableA:
    Value:
      Ref: PrivateRouteTableA
    Export:
      Name: !Sub '${Environment}-private-rt-a'
  PrivateRouteTableB:
    Value:
      Ref: PrivateRouteTableB
    Export:
      Name: !Sub '${Environment}-private-rt-b'
  PrivateRouteTableC:
    Value:
      Ref: PrivateRouteTableC
    Export:
      Name: !Sub '${Environment}-private-rt-c'
  VPCFlowLogsS3BucketName:
    Condition: EnableVPCFlowLogs
    Value:
      Ref: VPCFlowLogsS3BucketObject
    Export:
      Name: !Sub '${Environment}-VPC-Flowlogs-s3-bucket-name'
  NATGatewayEIPA:
    Condition: IsNATAEnabled
    Value:
      Ref: NATGatewayEIPA
    Export:
      Name: !Sub '${Environment}-NAT-gateway-elastic-IP-A'
  NATGatewayEIPB:
    Condition: IsNATBEnabled
    Value:
      Ref: NATGatewayEIPB
    Export:
      Name: !Sub '${Environment}-NAT-gateway-elastic-IP-B'
  NATGatewayEIPC:
    Condition: IsNATCEnabled
    Value:
      Ref: NATGatewayEIPC
    Export:
      Name: !Sub '${Environment}-NAT-gateway-elastic-IP-C'